config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  root 'quotes#index'
  # get 'quotes/index'

  # get 'quotes/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
	validates :quote, presence: true
	validates :url, presence:true

	def self.search(search)
		where("quote ILIKE ?", "%#{search}%")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
  	@all_quotes = Quote.page(params[:page]).per(25)
  	if params[:search]
  		@all_quotes = Quote.search(params[:search]).order("created_at DESC")
  	else
  		@all_quotes = Quote.all.order("created_at DESC")
  	end
  end

  def new
  	@quote = Quote.new
  end

  def create
  	@quote = Quote.new(params.require(:quote).permit(:quote, :url))
  	if @quote.save
  		redirect_to root_path
  	else
  		render "new"
  	end
  end

  def destroy
  	@quote = Quote.find(params[:id])
  	if @quote.destroy
  		#redirect_to root_path
  		redirect_back(fallback_location: root_path)
  	else
  		flash[:alert] = "Error deleting post"
  	end
  end

  def update
  	@quote = Quote.find(params[:id])
  	if @quote.update(params.require(:quote).permit(:quote, :url))
  		redirect_to root_path
  	else
  		render 'edit'
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Princess Carolyn Quotes</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<%= yield %>
	<%= form_tag(quotes_path, :method => "get", id: "search-form") do %>
	<%= text_field_tag :search, params[:search], placeholder: "Search quotes" %>
	<%= submit_tag "Search", :name => nil %>
	<% end %>

</body>
</html>

app/views/quotes/edit.html.erb
<h1>Edit Quote</h1>
<%= render 'quote' %>
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<h1 align="center">PRINCESS CAROLYN QUOTES</h1>
<% @all_quotes.each do |quote| %>
	<div class="layer">
	<% if @all_quotes.blank? %>
	<h4>There are no quotes containing the term <%= params[:search] %></h4>
	<% end %>



		<h2><%= link_to quote.quote, quote.url %></h2>
		<!-- <p><%= quote.quote %></p> -->
		<p><%= link_to "Delete Quote", quote,
		:confirm => "Are you sure?",
		:method => :delete %></p>

	</div>
<% end %>

<p class="myButton"><%= link_to "ADD A QUOTE", new_quote_path %></p>

app/views/quotes/new.html.erb
<%= simple_form_for @quote do |form| %>
  <%= form.input :quote, label: "Quote" %>
  <%= form.input :url, label: "Link to quote" %>
  <%= form.button :submit %>
<% end %>